"""Visualization Task that saves Data and Plots to a Markdown File."""

from scriptengine.tasks.base import Task
import jinja2
import os, glob
import yaml

class MarkdownOutput(Task):
    def __init__(self, parameters):
        required = [
            "exp_id",
            "src",
            "dst"
        ]
        super().__init__(__name__, parameters, required_parameters=required)
    
    def __repr__(self):
        return (
            f"{self.__class__.__name__}"
            f"({self.exp_id}, {self.src}, {self.dst})"
        )

    def run(self, context):
        scalars = self.load_yaml_files()
        # plots = ?
        
        env = jinja2.Environment(
            loader=jinja2.PackageLoader('ece-4-monitoring'),
            )
        md_template = env.get_template('monitoring.md.j2')
        
        with open(f"{self.dst}/monitoring.md", 'w') as md_out:
            md_out.write(md_template.render(
                exp_id = self.exp_id,
                scalar_diagnostics = scalars,
            ))
    
    def load_yaml_files(self):
        """Loads & returns the YAML files generated by processing tasks."""
        os.chdir(f"{self.src}")
        filepaths = [f"{self.src}/{filename}"
                     for filename in glob.glob(f"{self.exp_id}-*.yml")]
        dicts = []
        for path in filepaths:
            with open(path) as file: 
                dct = yaml.load(file, Loader = yaml.FullLoader)
                dicts.append(dct)
        return dicts