name: Download test data
on: workflow_call

env:
  TEST_DATA_REF: "https://github.com/valentinaschueller/ece-4-monitoring-test-data/archive/refs/heads/main.zip"
  TEST_DATA_DOWNLOAD: "${{HOME}}/test-data"


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Download test data
        run: |
          mkdir ${TEST_DATA_DOWNLOAD};
          wget -O ${TEST_DATA_DOWNLOAD}/test-data.zip ${TEST_DATA_REF};
          unzip -q ${TEST_DATA_DOWNLOAD}/test-data.zip -d ${TEST_DATA_DOWNLOAD};
      - name: Move to correct folder
        run: mv ${TEST_DATA_DOWNLOAD}/ece-4-monitoring-test-data-main/ tests/testdata;
