name: Test action
on: push

jobs:

  install:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{matrix.python-version}}
      -
        name: Install miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          environment-file: conda_environment.yml
          python-version: ${{matrix.python-version}}
      -
        name: Print info (1)
        run: |
          mamba info
          mamba list
          pip --version
      -
        name: Install cartopy apt deps
        run: |
          sudo apt install libgeos++-dev -y
      -
        name: Install se-t-ece from source
        run: |
          pip install -e .
      -
        name: Print info (2)
        run: |
          mamba info
          mamba list
          pip --version
